// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.i64().primaryKey(),
  chunkKey: __t.i64().name("chunk_key"),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  typeId: __t.u32().name("type_id"),
  typeName: __t.string().name("type_name"),
  blockStateId: __t.u32().name("block_state_id"),
  nbt: __t.byteArray(),
  nbtJson: __t.string().name("nbt_json"),
  computerId: __t.option(__t.i32()).name("computer_id"),
  label: __t.option(__t.string()),
  fuel: __t.option(__t.i32()),
  on: __t.option(__t.bool()),
  leftUpgrade: __t.option(__t.string()).name("left_upgrade"),
  rightUpgrade: __t.option(__t.string()).name("right_upgrade"),
  updatedAt: __t.timestamp().name("updated_at"),
});
