// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  seq: __t.u64().primaryKey(),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  oldStateId: __t.u32().name("old_state_id"),
  newStateId: __t.u32().name("new_state_id"),
  at: __t.timestamp(),
});
