// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.i64().primaryKey(),
  dimension: __t.string(),
  cx: __t.i32(),
  cz: __t.i32(),
  minSection: __t.i32().name("min_section"),
  sectionCount: __t.u32().name("section_count"),
  loadedAt: __t.timestamp().name("loaded_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
