// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.i64().primaryKey(),
  chunkKey: __t.i64().name("chunk_key"),
  cx: __t.i32(),
  cz: __t.i32(),
  sy: __t.i32(),
  skyLight: __t.byteArray().name("sky_light"),
  blockLight: __t.byteArray().name("block_light"),
  updatedAt: __t.timestamp().name("updated_at"),
});
