// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.i64().primaryKey(),
  chunkKey: __t.i64().name("chunk_key"),
  cx: __t.i32(),
  cz: __t.i32(),
  sy: __t.i32(),
  nonAirCount: __t.u16().name("non_air_count"),
  blockBits: __t.u8().name("block_bits"),
  blockPalette: __t.array(__t.u32()).name("block_palette"),
  blockData: __t.array(__t.u64()).name("block_data"),
  biomeBits: __t.u8().name("biome_bits"),
  biomePalette: __t.array(__t.u32()).name("biome_palette"),
  biomeData: __t.array(__t.u64()).name("biome_data"),
  updatedAt: __t.timestamp().name("updated_at"),
});
