// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  windowId: __t.i32().primaryKey().name("window_id"),
  menuType: __t.string().name("menu_type"),
  title: __t.string(),
  openedFromX: __t.option(__t.i32()).name("opened_from_x"),
  openedFromY: __t.option(__t.i32()).name("opened_from_y"),
  openedFromZ: __t.option(__t.i32()).name("opened_from_z"),
  slots: __t.array(__t.string()),
  carried: __t.string(),
  stateId: __t.i32().name("state_id"),
  undecodedComponent: __t.option(__t.string()).name("undecoded_component"),
  openedAt: __t.timestamp().name("opened_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
