// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  uuid: __t.string(),
  typeId: __t.u32().name("type_id"),
  typeName: __t.string().name("type_name"),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  headYaw: __t.f32().name("head_yaw"),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  data: __t.i32(),
  customName: __t.option(__t.string()).name("custom_name"),
  updatedAt: __t.timestamp().name("updated_at"),
  appearance: __t.option(__t.string()),
  equipment: __t.option(__t.string()),
});
