// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import ClearWorldReducer from "./clear_world_reducer";
import CloseAllContainersReducer from "./close_all_containers_reducer";
import CloseContainerReducer from "./close_container_reducer";
import CompleteBotCommandReducer from "./complete_bot_command_reducer";
import ExpirePendingBotCommandsReducer from "./expire_pending_bot_commands_reducer";
import MoveEntitiesReducer from "./move_entities_reducer";
import RemoveBlockEntitiesReducer from "./remove_block_entities_reducer";
import RemoveEntitiesReducer from "./remove_entities_reducer";
import RemoveMonitorsReducer from "./remove_monitors_reducer";
import RemovePlayersReducer from "./remove_players_reducer";
import RequestClickSlotReducer from "./request_click_slot_reducer";
import RequestCloseContainerReducer from "./request_close_container_reducer";
import RequestOpenContainerReducer from "./request_open_container_reducer";
import SetBlockStatesReducer from "./set_block_states_reducer";
import SetBotStatusReducer from "./set_bot_status_reducer";
import SetContainerSlotReducer from "./set_container_slot_reducer";
import SetEntityAppearanceReducer from "./set_entity_appearance_reducer";
import SetEntityEquipmentReducer from "./set_entity_equipment_reducer";
import SetEntityNameReducer from "./set_entity_name_reducer";
import SetRegistryEntriesReducer from "./set_registry_entries_reducer";
import SetTimeReducer from "./set_time_reducer";
import UnloadChunkReducer from "./unload_chunk_reducer";
import UpdateLightReducer from "./update_light_reducer";
import UpdateMonitorsReducer from "./update_monitors_reducer";
import UpdateSectionsReducer from "./update_sections_reducer";
import UpsertBlockEntitiesReducer from "./upsert_block_entities_reducer";
import UpsertChunkReducer from "./upsert_chunk_reducer";
import UpsertContainerReducer from "./upsert_container_reducer";
import UpsertEntitiesReducer from "./upsert_entities_reducer";
import UpsertPlayersReducer from "./upsert_players_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BlockChangeRow from "./block_change_table";
import BlockEntityRow from "./block_entity_table";
import BlockStateRow from "./block_state_table";
import BotCommandRow from "./bot_command_table";
import BotStatusRow from "./bot_status_table";
import ChunkRow from "./chunk_table";
import ChunkLightRow from "./chunk_light_table";
import ChunkSectionRow from "./chunk_section_table";
import ContainerRow from "./container_table";
import EntityRow from "./entity_table";
import MonitorRow from "./monitor_table";
import PlayerRow from "./player_table";
import RegistryEntryRow from "./registry_entry_table";
import WorldTimeRow from "./world_time_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  blockChange: __table({
    name: 'block_change',
    indexes: [
      { accessor: 'seq', name: 'block_change_seq_idx_btree', algorithm: 'btree', columns: [
        'seq',
      ] },
    ],
    constraints: [
      { name: 'block_change_seq_key', constraint: 'unique', columns: ['seq'] },
    ],
  }, BlockChangeRow),
  blockEntity: __table({
    name: 'block_entity',
    indexes: [
      { accessor: 'chunk_key', name: 'block_entity_chunk_key_idx_btree', algorithm: 'btree', columns: [
        'chunkKey',
      ] },
      { accessor: 'computer_id', name: 'block_entity_computer_id_idx_btree', algorithm: 'btree', columns: [
        'computerId',
      ] },
      { accessor: 'key', name: 'block_entity_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'type_name', name: 'block_entity_type_name_idx_btree', algorithm: 'btree', columns: [
        'typeName',
      ] },
    ],
    constraints: [
      { name: 'block_entity_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, BlockEntityRow),
  blockState: __table({
    name: 'block_state',
    indexes: [
      { accessor: 'id', name: 'block_state_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'block_state_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'block_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BlockStateRow),
  botCommand: __table({
    name: 'bot_command',
    indexes: [
      { accessor: 'id', name: 'bot_command_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'status', name: 'bot_command_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'bot_command_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BotCommandRow),
  botStatus: __table({
    name: 'bot_status',
    indexes: [
      { accessor: 'id', name: 'bot_status_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'bot_status_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BotStatusRow),
  chunk: __table({
    name: 'chunk',
    indexes: [
      { accessor: 'cx', name: 'chunk_cx_idx_btree', algorithm: 'btree', columns: [
        'cx',
      ] },
      { accessor: 'cz', name: 'chunk_cz_idx_btree', algorithm: 'btree', columns: [
        'cz',
      ] },
      { accessor: 'key', name: 'chunk_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'chunk_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ChunkRow),
  chunkLight: __table({
    name: 'chunk_light',
    indexes: [
      { accessor: 'chunk_key', name: 'chunk_light_chunk_key_idx_btree', algorithm: 'btree', columns: [
        'chunkKey',
      ] },
      { accessor: 'key', name: 'chunk_light_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'chunk_light_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ChunkLightRow),
  chunkSection: __table({
    name: 'chunk_section',
    indexes: [
      { accessor: 'chunk_key', name: 'chunk_section_chunk_key_idx_btree', algorithm: 'btree', columns: [
        'chunkKey',
      ] },
      { accessor: 'key', name: 'chunk_section_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'chunk_section_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ChunkSectionRow),
  container: __table({
    name: 'container',
    indexes: [
      { accessor: 'window_id', name: 'container_window_id_idx_btree', algorithm: 'btree', columns: [
        'windowId',
      ] },
    ],
    constraints: [
      { name: 'container_window_id_key', constraint: 'unique', columns: ['windowId'] },
    ],
  }, ContainerRow),
  entity: __table({
    name: 'entity',
    indexes: [
      { accessor: 'id', name: 'entity_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'type_name', name: 'entity_type_name_idx_btree', algorithm: 'btree', columns: [
        'typeName',
      ] },
    ],
    constraints: [
      { name: 'entity_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EntityRow),
  monitor: __table({
    name: 'monitor',
    indexes: [
      { accessor: 'chunk_key', name: 'monitor_chunk_key_idx_btree', algorithm: 'btree', columns: [
        'chunkKey',
      ] },
      { accessor: 'key', name: 'monitor_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'monitor_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, MonitorRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'name', name: 'player_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
      { accessor: 'uuid', name: 'player_uuid_idx_btree', algorithm: 'btree', columns: [
        'uuid',
      ] },
    ],
    constraints: [
      { name: 'player_uuid_key', constraint: 'unique', columns: ['uuid'] },
    ],
  }, PlayerRow),
  registryEntry: __table({
    name: 'registry_entry',
    indexes: [
      { accessor: 'key', name: 'registry_entry_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'by_registry_id', name: 'registry_entry_registry_id_idx_btree', algorithm: 'btree', columns: [
        'registry',
        'id',
      ] },
    ],
    constraints: [
      { name: 'registry_entry_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, RegistryEntryRow),
  worldTime: __table({
    name: 'world_time',
    indexes: [
      { accessor: 'dimension', name: 'world_time_dimension_idx_btree', algorithm: 'btree', columns: [
        'dimension',
      ] },
    ],
    constraints: [
      { name: 'world_time_dimension_key', constraint: 'unique', columns: ['dimension'] },
    ],
  }, WorldTimeRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("clear_world", ClearWorldReducer),
  __reducerSchema("close_all_containers", CloseAllContainersReducer),
  __reducerSchema("close_container", CloseContainerReducer),
  __reducerSchema("complete_bot_command", CompleteBotCommandReducer),
  __reducerSchema("expire_pending_bot_commands", ExpirePendingBotCommandsReducer),
  __reducerSchema("move_entities", MoveEntitiesReducer),
  __reducerSchema("remove_block_entities", RemoveBlockEntitiesReducer),
  __reducerSchema("remove_entities", RemoveEntitiesReducer),
  __reducerSchema("remove_monitors", RemoveMonitorsReducer),
  __reducerSchema("remove_players", RemovePlayersReducer),
  __reducerSchema("request_click_slot", RequestClickSlotReducer),
  __reducerSchema("request_close_container", RequestCloseContainerReducer),
  __reducerSchema("request_open_container", RequestOpenContainerReducer),
  __reducerSchema("set_block_states", SetBlockStatesReducer),
  __reducerSchema("set_bot_status", SetBotStatusReducer),
  __reducerSchema("set_container_slot", SetContainerSlotReducer),
  __reducerSchema("set_entity_appearance", SetEntityAppearanceReducer),
  __reducerSchema("set_entity_equipment", SetEntityEquipmentReducer),
  __reducerSchema("set_entity_name", SetEntityNameReducer),
  __reducerSchema("set_registry_entries", SetRegistryEntriesReducer),
  __reducerSchema("set_time", SetTimeReducer),
  __reducerSchema("unload_chunk", UnloadChunkReducer),
  __reducerSchema("update_light", UpdateLightReducer),
  __reducerSchema("update_monitors", UpdateMonitorsReducer),
  __reducerSchema("update_sections", UpdateSectionsReducer),
  __reducerSchema("upsert_block_entities", UpsertBlockEntitiesReducer),
  __reducerSchema("upsert_chunk", UpsertChunkReducer),
  __reducerSchema("upsert_container", UpsertContainerReducer),
  __reducerSchema("upsert_entities", UpsertEntitiesReducer),
  __reducerSchema("upsert_players", UpsertPlayersReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `blockChange` instead. This alias will be removed in the next major version. */
    readonly "block_change": Omit<typeof tablesSchema.schemaType.tables["blockChange"], "accessorName"> & { readonly accessorName: "block_change" };
    /** @deprecated Use `blockEntity` instead. This alias will be removed in the next major version. */
    readonly "block_entity": Omit<typeof tablesSchema.schemaType.tables["blockEntity"], "accessorName"> & { readonly accessorName: "block_entity" };
    /** @deprecated Use `blockState` instead. This alias will be removed in the next major version. */
    readonly "block_state": Omit<typeof tablesSchema.schemaType.tables["blockState"], "accessorName"> & { readonly accessorName: "block_state" };
    /** @deprecated Use `botCommand` instead. This alias will be removed in the next major version. */
    readonly "bot_command": Omit<typeof tablesSchema.schemaType.tables["botCommand"], "accessorName"> & { readonly accessorName: "bot_command" };
    /** @deprecated Use `botStatus` instead. This alias will be removed in the next major version. */
    readonly "bot_status": Omit<typeof tablesSchema.schemaType.tables["botStatus"], "accessorName"> & { readonly accessorName: "bot_status" };
    /** @deprecated Use `chunkLight` instead. This alias will be removed in the next major version. */
    readonly "chunk_light": Omit<typeof tablesSchema.schemaType.tables["chunkLight"], "accessorName"> & { readonly accessorName: "chunk_light" };
    /** @deprecated Use `chunkSection` instead. This alias will be removed in the next major version. */
    readonly "chunk_section": Omit<typeof tablesSchema.schemaType.tables["chunkSection"], "accessorName"> & { readonly accessorName: "chunk_section" };
    /** @deprecated Use `registryEntry` instead. This alias will be removed in the next major version. */
    readonly "registry_entry": Omit<typeof tablesSchema.schemaType.tables["registryEntry"], "accessorName"> & { readonly accessorName: "registry_entry" };
    /** @deprecated Use `worldTime` instead. This alias will be removed in the next major version. */
    readonly "world_time": Omit<typeof tablesSchema.schemaType.tables["worldTime"], "accessorName"> & { readonly accessorName: "world_time" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "block_change": "blockChange",
  "block_entity": "blockEntity",
  "block_state": "blockState",
  "bot_command": "botCommand",
  "bot_status": "botStatus",
  "chunk_light": "chunkLight",
  "chunk_section": "chunkSection",
  "registry_entry": "registryEntry",
  "world_time": "worldTime",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `blockChange` instead. This alias will be removed in the next major version. */
  readonly "block_change": __DbViewBase["blockChange"];
  /** @deprecated Use `blockEntity` instead. This alias will be removed in the next major version. */
  readonly "block_entity": __DbViewBase["blockEntity"];
  /** @deprecated Use `blockState` instead. This alias will be removed in the next major version. */
  readonly "block_state": __DbViewBase["blockState"];
  /** @deprecated Use `botCommand` instead. This alias will be removed in the next major version. */
  readonly "bot_command": __DbViewBase["botCommand"];
  /** @deprecated Use `botStatus` instead. This alias will be removed in the next major version. */
  readonly "bot_status": __DbViewBase["botStatus"];
  /** @deprecated Use `chunkLight` instead. This alias will be removed in the next major version. */
  readonly "chunk_light": __DbViewBase["chunkLight"];
  /** @deprecated Use `chunkSection` instead. This alias will be removed in the next major version. */
  readonly "chunk_section": __DbViewBase["chunkSection"];
  /** @deprecated Use `registryEntry` instead. This alias will be removed in the next major version. */
  readonly "registry_entry": __DbViewBase["registryEntry"];
  /** @deprecated Use `worldTime` instead. This alias will be removed in the next major version. */
  readonly "world_time": __DbViewBase["worldTime"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `blockChange` instead. This alias will be removed in the next major version. */
  readonly "block_change": __TablesBase["blockChange"];
  /** @deprecated Use `blockEntity` instead. This alias will be removed in the next major version. */
  readonly "block_entity": __TablesBase["blockEntity"];
  /** @deprecated Use `blockState` instead. This alias will be removed in the next major version. */
  readonly "block_state": __TablesBase["blockState"];
  /** @deprecated Use `botCommand` instead. This alias will be removed in the next major version. */
  readonly "bot_command": __TablesBase["botCommand"];
  /** @deprecated Use `botStatus` instead. This alias will be removed in the next major version. */
  readonly "bot_status": __TablesBase["botStatus"];
  /** @deprecated Use `chunkLight` instead. This alias will be removed in the next major version. */
  readonly "chunk_light": __TablesBase["chunkLight"];
  /** @deprecated Use `chunkSection` instead. This alias will be removed in the next major version. */
  readonly "chunk_section": __TablesBase["chunkSection"];
  /** @deprecated Use `registryEntry` instead. This alias will be removed in the next major version. */
  readonly "registry_entry": __TablesBase["registryEntry"];
  /** @deprecated Use `worldTime` instead. This alias will be removed in the next major version. */
  readonly "world_time": __TablesBase["worldTime"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

