// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.i64().primaryKey(),
  chunkKey: __t.i64().name("chunk_key"),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  facing: __t.string(),
  blockWidth: __t.u32().name("block_width"),
  blockHeight: __t.u32().name("block_height"),
  termWidth: __t.u32().name("term_width"),
  termHeight: __t.u32().name("term_height"),
  colour: __t.bool(),
  cursorX: __t.i32().name("cursor_x"),
  cursorY: __t.i32().name("cursor_y"),
  cursorBlink: __t.bool().name("cursor_blink"),
  cursorFg: __t.u8().name("cursor_fg"),
  cursorBg: __t.u8().name("cursor_bg"),
  hasScreen: __t.bool().name("has_screen"),
  lines: __t.array(__t.string()),
  fg: __t.array(__t.string()),
  bg: __t.array(__t.string()),
  palette: __t.array(__t.string()),
  updatedAt: __t.timestamp().name("updated_at"),
});
