// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  uuid: __t.string().primaryKey(),
  name: __t.string(),
  entityId: __t.option(__t.i32()).name("entity_id"),
  online: __t.bool(),
  gamemode: __t.i32(),
  latency: __t.i32(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
