// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  serverAddr: __t.string(),
  username: __t.string(),
  state: __t.string(),
  detail: __t.string(),
  dimension: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  viewDistance: __t.i32(),
  chunksLoaded: __t.u32(),
  packetsSeen: __t.u64(),
};
