// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BlockChange = __t.object("BlockChange", {
  seq: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  oldStateId: __t.u32(),
  newStateId: __t.u32(),
  at: __t.timestamp(),
});
export type BlockChange = __Infer<typeof BlockChange>;

export const BlockChangeData = __t.object("BlockChangeData", {
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  oldStateId: __t.u32(),
  newStateId: __t.u32(),
});
export type BlockChangeData = __Infer<typeof BlockChangeData>;

export const BlockEntity = __t.object("BlockEntity", {
  key: __t.i64(),
  chunkKey: __t.i64(),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  typeId: __t.u32(),
  typeName: __t.string(),
  blockStateId: __t.u32(),
  nbt: __t.byteArray(),
  nbtJson: __t.string(),
  computerId: __t.option(__t.i32()),
  label: __t.option(__t.string()),
  fuel: __t.option(__t.i32()),
  on: __t.option(__t.bool()),
  leftUpgrade: __t.option(__t.string()),
  rightUpgrade: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type BlockEntity = __Infer<typeof BlockEntity>;

export const BlockEntityData = __t.object("BlockEntityData", {
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  typeId: __t.u32(),
  typeName: __t.string(),
  blockStateId: __t.u32(),
  nbt: __t.byteArray(),
  nbtJson: __t.string(),
  computerId: __t.option(__t.i32()),
  label: __t.option(__t.string()),
  fuel: __t.option(__t.i32()),
  on: __t.option(__t.bool()),
  leftUpgrade: __t.option(__t.string()),
  rightUpgrade: __t.option(__t.string()),
});
export type BlockEntityData = __Infer<typeof BlockEntityData>;

export const BlockStateDef = __t.object("BlockStateDef", {
  id: __t.u32(),
  name: __t.string(),
  properties: __t.string(),
});
export type BlockStateDef = __Infer<typeof BlockStateDef>;

export const BlockStateRow = __t.object("BlockStateRow", {
  id: __t.u32(),
  name: __t.string(),
  properties: __t.string(),
});
export type BlockStateRow = __Infer<typeof BlockStateRow>;

export const BotCommand = __t.object("BotCommand", {
  id: __t.u64(),
  kind: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  face: __t.string(),
  status: __t.string(),
  detail: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  windowId: __t.i32(),
  slot: __t.i32(),
  button: __t.i32(),
  mode: __t.i32(),
});
export type BotCommand = __Infer<typeof BotCommand>;

export const BotStatus = __t.object("BotStatus", {
  id: __t.u32(),
  serverAddr: __t.string(),
  username: __t.string(),
  state: __t.string(),
  detail: __t.string(),
  dimension: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  viewDistance: __t.i32(),
  chunksLoaded: __t.u32(),
  packetsSeen: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type BotStatus = __Infer<typeof BotStatus>;

export const Chunk = __t.object("Chunk", {
  key: __t.i64(),
  dimension: __t.string(),
  cx: __t.i32(),
  cz: __t.i32(),
  minSection: __t.i32(),
  sectionCount: __t.u32(),
  loadedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Chunk = __Infer<typeof Chunk>;

export const ChunkLight = __t.object("ChunkLight", {
  key: __t.i64(),
  chunkKey: __t.i64(),
  cx: __t.i32(),
  cz: __t.i32(),
  sy: __t.i32(),
  skyLight: __t.byteArray(),
  blockLight: __t.byteArray(),
  updatedAt: __t.timestamp(),
});
export type ChunkLight = __Infer<typeof ChunkLight>;

export const ChunkSection = __t.object("ChunkSection", {
  key: __t.i64(),
  chunkKey: __t.i64(),
  cx: __t.i32(),
  cz: __t.i32(),
  sy: __t.i32(),
  nonAirCount: __t.u16(),
  blockBits: __t.u8(),
  blockPalette: __t.array(__t.u32()),
  blockData: __t.array(__t.u64()),
  biomeBits: __t.u8(),
  biomePalette: __t.array(__t.u32()),
  biomeData: __t.array(__t.u64()),
  updatedAt: __t.timestamp(),
});
export type ChunkSection = __Infer<typeof ChunkSection>;

export const Container = __t.object("Container", {
  windowId: __t.i32(),
  menuType: __t.string(),
  title: __t.string(),
  openedFromX: __t.option(__t.i32()),
  openedFromY: __t.option(__t.i32()),
  openedFromZ: __t.option(__t.i32()),
  slots: __t.array(__t.string()),
  carried: __t.string(),
  stateId: __t.i32(),
  undecodedComponent: __t.option(__t.string()),
  openedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Container = __Infer<typeof Container>;

export const ContainerData = __t.object("ContainerData", {
  windowId: __t.i32(),
  menuType: __t.string(),
  title: __t.string(),
  openedFromX: __t.option(__t.i32()),
  openedFromY: __t.option(__t.i32()),
  openedFromZ: __t.option(__t.i32()),
  slots: __t.array(__t.string()),
  carried: __t.string(),
  stateId: __t.i32(),
  undecodedComponent: __t.option(__t.string()),
});
export type ContainerData = __Infer<typeof ContainerData>;

export const Entity = __t.object("Entity", {
  id: __t.i32(),
  uuid: __t.string(),
  typeId: __t.u32(),
  typeName: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  headYaw: __t.f32(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  data: __t.i32(),
  customName: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
  appearance: __t.option(__t.string()),
  equipment: __t.option(__t.string()),
});
export type Entity = __Infer<typeof Entity>;

export const EntityData = __t.object("EntityData", {
  id: __t.i32(),
  uuid: __t.string(),
  typeId: __t.u32(),
  typeName: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  headYaw: __t.f32(),
  vx: __t.f64(),
  vy: __t.f64(),
  vz: __t.f64(),
  data: __t.i32(),
});
export type EntityData = __Infer<typeof EntityData>;

export const EntityMove = __t.object("EntityMove", {
  id: __t.i32(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  headYaw: __t.f32(),
});
export type EntityMove = __Infer<typeof EntityMove>;

export const LightData = __t.object("LightData", {
  sy: __t.i32(),
  skyLight: __t.byteArray(),
  blockLight: __t.byteArray(),
});
export type LightData = __Infer<typeof LightData>;

export const Monitor = __t.object("Monitor", {
  key: __t.i64(),
  chunkKey: __t.i64(),
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  facing: __t.string(),
  blockWidth: __t.u32(),
  blockHeight: __t.u32(),
  termWidth: __t.u32(),
  termHeight: __t.u32(),
  colour: __t.bool(),
  cursorX: __t.i32(),
  cursorY: __t.i32(),
  cursorBlink: __t.bool(),
  cursorFg: __t.u8(),
  cursorBg: __t.u8(),
  hasScreen: __t.bool(),
  lines: __t.array(__t.string()),
  fg: __t.array(__t.string()),
  bg: __t.array(__t.string()),
  palette: __t.array(__t.string()),
  updatedAt: __t.timestamp(),
});
export type Monitor = __Infer<typeof Monitor>;

export const MonitorData = __t.object("MonitorData", {
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
  facing: __t.string(),
  blockWidth: __t.u32(),
  blockHeight: __t.u32(),
  termWidth: __t.u32(),
  termHeight: __t.u32(),
  colour: __t.bool(),
  cursorX: __t.i32(),
  cursorY: __t.i32(),
  cursorBlink: __t.bool(),
  cursorFg: __t.u8(),
  cursorBg: __t.u8(),
  hasScreen: __t.bool(),
  lines: __t.array(__t.string()),
  fg: __t.array(__t.string()),
  bg: __t.array(__t.string()),
  palette: __t.array(__t.string()),
});
export type MonitorData = __Infer<typeof MonitorData>;

export const Player = __t.object("Player", {
  uuid: __t.string(),
  name: __t.string(),
  entityId: __t.option(__t.i32()),
  online: __t.bool(),
  gamemode: __t.i32(),
  latency: __t.i32(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerData = __t.object("PlayerData", {
  uuid: __t.string(),
  name: __t.string(),
  entityId: __t.option(__t.i32()),
  online: __t.bool(),
  gamemode: __t.i32(),
  latency: __t.i32(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  yaw: __t.f32(),
  pitch: __t.f32(),
});
export type PlayerData = __Infer<typeof PlayerData>;

export const RegistryDef = __t.object("RegistryDef", {
  registry: __t.string(),
  id: __t.u32(),
  name: __t.string(),
});
export type RegistryDef = __Infer<typeof RegistryDef>;

export const RegistryEntry = __t.object("RegistryEntry", {
  key: __t.string(),
  registry: __t.string(),
  id: __t.u32(),
  name: __t.string(),
});
export type RegistryEntry = __Infer<typeof RegistryEntry>;

export const SectionData = __t.object("SectionData", {
  sy: __t.i32(),
  nonAirCount: __t.u16(),
  blockBits: __t.u8(),
  blockPalette: __t.array(__t.u32()),
  blockData: __t.array(__t.u64()),
  biomeBits: __t.u8(),
  biomePalette: __t.array(__t.u32()),
  biomeData: __t.array(__t.u64()),
  skyLight: __t.byteArray(),
  blockLight: __t.byteArray(),
});
export type SectionData = __Infer<typeof SectionData>;

export const WorldTime = __t.object("WorldTime", {
  dimension: __t.string(),
  gameTime: __t.i64(),
  dayTime: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type WorldTime = __Infer<typeof WorldTime>;

