// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SectionData,
  BlockEntityData,
} from "./types";

export default {
  dimension: __t.string(),
  cx: __t.i32(),
  cz: __t.i32(),
  minSection: __t.i32(),
  get sections() {
    return __t.array(SectionData);
  },
  get blockEntities() {
    return __t.array(BlockEntityData);
  },
};
