// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClearWorldReducer from "../clear_world_reducer";
import CloseAllContainersReducer from "../close_all_containers_reducer";
import CloseContainerReducer from "../close_container_reducer";
import CompleteBotCommandReducer from "../complete_bot_command_reducer";
import ExpirePendingBotCommandsReducer from "../expire_pending_bot_commands_reducer";
import MoveEntitiesReducer from "../move_entities_reducer";
import RemoveBlockEntitiesReducer from "../remove_block_entities_reducer";
import RemoveEntitiesReducer from "../remove_entities_reducer";
import RemoveMonitorsReducer from "../remove_monitors_reducer";
import RemovePlayersReducer from "../remove_players_reducer";
import RequestClickSlotReducer from "../request_click_slot_reducer";
import RequestCloseContainerReducer from "../request_close_container_reducer";
import RequestOpenContainerReducer from "../request_open_container_reducer";
import SetBlockStatesReducer from "../set_block_states_reducer";
import SetBotStatusReducer from "../set_bot_status_reducer";
import SetContainerSlotReducer from "../set_container_slot_reducer";
import SetEntityAppearanceReducer from "../set_entity_appearance_reducer";
import SetEntityEquipmentReducer from "../set_entity_equipment_reducer";
import SetEntityNameReducer from "../set_entity_name_reducer";
import SetRegistryEntriesReducer from "../set_registry_entries_reducer";
import SetTimeReducer from "../set_time_reducer";
import UnloadChunkReducer from "../unload_chunk_reducer";
import UpdateLightReducer from "../update_light_reducer";
import UpdateMonitorsReducer from "../update_monitors_reducer";
import UpdateSectionsReducer from "../update_sections_reducer";
import UpsertBlockEntitiesReducer from "../upsert_block_entities_reducer";
import UpsertChunkReducer from "../upsert_chunk_reducer";
import UpsertContainerReducer from "../upsert_container_reducer";
import UpsertEntitiesReducer from "../upsert_entities_reducer";
import UpsertPlayersReducer from "../upsert_players_reducer";

export type ClearWorldParams = __Infer<typeof ClearWorldReducer>;
export type CloseAllContainersParams = __Infer<typeof CloseAllContainersReducer>;
export type CloseContainerParams = __Infer<typeof CloseContainerReducer>;
export type CompleteBotCommandParams = __Infer<typeof CompleteBotCommandReducer>;
export type ExpirePendingBotCommandsParams = __Infer<typeof ExpirePendingBotCommandsReducer>;
export type MoveEntitiesParams = __Infer<typeof MoveEntitiesReducer>;
export type RemoveBlockEntitiesParams = __Infer<typeof RemoveBlockEntitiesReducer>;
export type RemoveEntitiesParams = __Infer<typeof RemoveEntitiesReducer>;
export type RemoveMonitorsParams = __Infer<typeof RemoveMonitorsReducer>;
export type RemovePlayersParams = __Infer<typeof RemovePlayersReducer>;
export type RequestClickSlotParams = __Infer<typeof RequestClickSlotReducer>;
export type RequestCloseContainerParams = __Infer<typeof RequestCloseContainerReducer>;
export type RequestOpenContainerParams = __Infer<typeof RequestOpenContainerReducer>;
export type SetBlockStatesParams = __Infer<typeof SetBlockStatesReducer>;
export type SetBotStatusParams = __Infer<typeof SetBotStatusReducer>;
export type SetContainerSlotParams = __Infer<typeof SetContainerSlotReducer>;
export type SetEntityAppearanceParams = __Infer<typeof SetEntityAppearanceReducer>;
export type SetEntityEquipmentParams = __Infer<typeof SetEntityEquipmentReducer>;
export type SetEntityNameParams = __Infer<typeof SetEntityNameReducer>;
export type SetRegistryEntriesParams = __Infer<typeof SetRegistryEntriesReducer>;
export type SetTimeParams = __Infer<typeof SetTimeReducer>;
export type UnloadChunkParams = __Infer<typeof UnloadChunkReducer>;
export type UpdateLightParams = __Infer<typeof UpdateLightReducer>;
export type UpdateMonitorsParams = __Infer<typeof UpdateMonitorsReducer>;
export type UpdateSectionsParams = __Infer<typeof UpdateSectionsReducer>;
export type UpsertBlockEntitiesParams = __Infer<typeof UpsertBlockEntitiesReducer>;
export type UpsertChunkParams = __Infer<typeof UpsertChunkReducer>;
export type UpsertContainerParams = __Infer<typeof UpsertContainerReducer>;
export type UpsertEntitiesParams = __Infer<typeof UpsertEntitiesReducer>;
export type UpsertPlayersParams = __Infer<typeof UpsertPlayersReducer>;

