/**
 * Tests against the REAL extracted table, not a fixture.
 *
 * This loads `public/physics.json` — the actual output of
 * `harness/src/mcextract/ExtractPhysics.java` — and checks facts about Minecraft that are
 * independently known: stone is 1.5 to break, obsidian is 50, bedrock is unbreakable, a
 * bottom slab is half a block tall, a torch has no collision box at all.
 *
 * The point is not to re-test Minecraft. It is that this file is the input to the
 * character controller, it is regenerated by a JVM harness that is easy to break silently,
 * and the failure mode of a broken regeneration is "movement feels subtly wrong" rather
 * than an error. If the shape palette indices shift, or the state-key format drifts away
 * from what `src/core/chunk.ts` produces, or the collapse optimisation eats a block, these
 * fail loudly instead.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { blockShapes, modelBounds, FULL_CUBE } from './block-shapes.js';
import { motionFrom, type PhysicsData } from './physics.js';
import type { World } from '../render/world.js';
import type { NavWorld } from './pathfind.js';

const PATH = 'public/physics.json';
const present = existsSync(PATH);
const physics: PhysicsData | null = present
  ? (JSON.parse(readFileSync(PATH, 'utf8')) as PhysicsData)
  : null;

/** Skipped rather than failed on a checkout that has not run the harness. */
const opts = { skip: present ? false : `${PATH} not built — run harness/run.sh` };

/** The boxes for a state, resolved the way the client resolves them. */
function boxesFor(stateKey: string): readonly (readonly number[])[] {
  const info = physics!.blocks[stateKey] ?? physics!.blocks[stateKey.split('[')[0]];
  assert.ok(info, `no row for ${stateKey} — the extraction or the key format changed`);
  return physics!.shapes[info.s];
}

function hardnessFor(stateKey: string): number {
  const info = physics!.blocks[stateKey] ?? physics!.blocks[stateKey.split('[')[0]];
  assert.ok(info, `no row for ${stateKey}`);
  return info.h;
}

// ---------------------------------------------------------------------------
// The player constants.

test('the extracted player constants are the game\'s, not a guess', opts, () => {
  const p = physics!.player;
  assert.equal(p.gravity, 0.08, 'gravity is not vanilla 0.08 blocks/tick^2');
  assert.ok(Math.abs(p.jumpStrength - 0.42) < 1e-6, 'jump strength is not vanilla 0.42');
  assert.equal(p.stepHeight, 0.6, 'step height is not vanilla 0.6 — slabs would stop being steppable');
  assert.equal(p.width, 0.6);
  assert.equal(p.height, 1.8);
  assert.ok(Math.abs(p.eyeHeight - 1.62) < 1e-6);
  assert.equal(p.sneakingSpeed, 0.3);
  assert.equal(p.sprintOperation, 'ADD_MULTIPLIED_TOTAL',
    'the sprint operation changed; physics.ts interprets the amount based on it');
});

test('the per-tick constants convert to the per-second ones the integrator uses', opts, () => {
  const m = motionFrom(physics!.player);
  assert.ok(Math.abs(m.gravity - 32) < 1e-6, `gravity became ${m.gravity} blocks/s^2, expected 32`);
  assert.ok(Math.abs(m.jumpSpeed - 8.4) < 1e-4, `jump became ${m.jumpSpeed} blocks/s, expected 8.4`);
  assert.ok(Math.abs(m.sprintMultiplier - 1.3) < 1e-6, 'ADD_MULTIPLIED_TOTAL 0.3 must become x1.3');
  assert.equal(m.measured, true);
  // Vanilla's jump apex, v^2/2g, is about 1.1 blocks. A wrong unit conversion shows up here
  // as a jump of 0.003 blocks or of 440, both of which are unmistakable.
  const apex = (m.jumpSpeed * m.jumpSpeed) / (2 * m.gravity);
  assert.ok(apex > 1 && apex < 1.3, `a jump would peak at ${apex} blocks`);
});

test('reach is the real interaction range, which is NOT the 5 the raycast assumes', opts, () => {
  assert.equal(physics!.player.blockInteractionRange, 4.5);
});

// ---------------------------------------------------------------------------
// Blocks: independently-known facts.

test('hardness matches what the game charges for these blocks', opts, () => {
  assert.equal(hardnessFor('minecraft:stone'), 1.5);
  assert.equal(hardnessFor('minecraft:obsidian'), 50);
  assert.equal(hardnessFor('minecraft:dirt'), 0.5);
  assert.equal(hardnessFor('minecraft:bedrock'), -1, 'bedrock must be unbreakable (-1)');
});

test('a bottom slab is half a block, which is the whole reason for this table', opts, () => {
  const boxes = boxesFor('minecraft:oak_slab[type=bottom,waterlogged=false]');
  assert.equal(boxes.length, 1);
  assert.deepEqual([...boxes[0]], [0, 0, 0, 1, 0.5, 1]);
});

test('a top slab sits in the TOP half, not the bottom', opts, () => {
  const boxes = boxesFor('minecraft:oak_slab[type=top,waterlogged=false]');
  assert.deepEqual([...boxes[0]], [0, 0.5, 0, 1, 1, 1]);
});

test('a full block is a full cube', opts, () => {
  assert.deepEqual([...boxesFor('minecraft:stone')[0]], [0, 0, 0, 1, 1, 1]);
});

test('things you walk through have NO collision box', opts, () => {
  for (const id of ['minecraft:torch', 'minecraft:water[level=0]', 'minecraft:poppy', 'minecraft:air']) {
    assert.equal(boxesFor(id).length, 0, `${id} should have no collision box`);
  }
});

test('a stair has more than one box — it is not a cube and never was', opts, () => {
  const boxes = boxesFor(
    'minecraft:oak_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]');
  assert.ok(boxes.length >= 2, `a stair resolved to ${boxes.length} box(es)`);
  const top = Math.max(...boxes.map((b) => b[4]));
  const bottom = Math.min(...boxes.map((b) => b[1]));
  assert.equal(bottom, 0);
  assert.equal(top, 1);
});

test('the state-key format matches what chunk.ts produces: properties SORTED', opts, () => {
  // chunk.ts documents "canonical name[k=v,k=v] with properties sorted". If the harness
  // stops sorting, every multi-state lookup misses and falls silently back to the guess.
  const keys = Object.keys(physics!.blocks).filter((k) => k.includes('['));
  assert.ok(keys.length > 100, 'no multi-property rows at all — the collapse ate everything');
  for (const k of keys.slice(0, 200)) {
    const props = k.slice(k.indexOf('[') + 1, -1).split(',').map((p) => p.split('=')[0]);
    const sorted = [...props].sort();
    assert.deepEqual(props, sorted, `properties are not sorted in ${k}`);
  }
});

test('the collapse kept both kinds of row reachable', opts, () => {
  // A uniform block is stored under its plain id...
  assert.ok(physics!.blocks['minecraft:stone'], 'the collapsed (plain-id) row is missing');
  // ...and a state-dependent one per state.
  assert.ok(physics!.blocks['minecraft:oak_slab[type=top,waterlogged=false]'],
    'the per-state row is missing');
});

// ---------------------------------------------------------------------------
// The resolution tiers.

/** Minimal stand-ins: blockShapes only needs a palette, getState and `known`. */
function stubWorld(palette: string[]): World {
  return {
    palette,
    getState: (x: number) => (x >= 0 && x < palette.length ? x : 0),
  } as unknown as World;
}

function stubNav(known = true): NavWorld {
  return { classify: () => 'solid', known: () => known };
}

test('tier 1: a vanilla block gets its exact extracted shape', opts, () => {
  const world = stubWorld(['minecraft:air', 'minecraft:oak_slab[type=bottom,waterlogged=false]']);
  const shapes = blockShapes(world, stubNav(), physics);
  const boxes = shapes.boxesAt(1, 10, 0);
  assert.equal(boxes.length, 1);
  // World coordinates, so the cell offset is applied.
  assert.deepEqual([...boxes[0]], [1, 10, 0, 2, 10.5, 1]);
  assert.equal(shapes.coverage().extracted, 1);
  assert.equal(shapes.hardnessAt(1, 10, 0), 2);
});

test('tier 2: an unknown MODDED block falls back to its own model bounds', () => {
  const world = stubWorld(['minecraft:air', 'create:shaft[axis=y]']);
  const quads = new Float32Array([0.375, 0, 0.375, 0.625, 1, 0.625]);
  const shapes = blockShapes(world, stubNav(), physics, () => quads);
  const boxes = shapes.boxesAt(1, 0, 0);
  assert.equal(shapes.coverage().model, 1, 'the model tier was not used for a modded block');
  assert.deepEqual([...boxes[0]], [1.375, 0, 0.375, 1.625, 1, 0.625]);
});

test('tier 3: with no table and no model, a solid block is a whole cube', () => {
  const world = stubWorld(['minecraft:air', 'somemod:mystery_block']);
  const shapes = blockShapes(world, stubNav(), null);
  assert.deepEqual([...shapes.boxesAt(1, 0, 0)[0]], [1, 0, 0, 2, 1, 1]);
  assert.equal(shapes.coverage().heuristic, 1);
});

test('a block the heuristic calls walk-through stays walk-through, model or not', () => {
  // A flower's model is two crossed quads; deriving a box from it would wall off every
  // plant in the world. The model tier must not fire for blocks already known passable.
  const world = stubWorld(['minecraft:air', 'somemod:pretty_flower']);
  const quads = new Float32Array([0, 0, 0, 1, 1, 1]);
  const shapes = blockShapes(world, stubNav(), null, () => quads);
  assert.equal(shapes.boxesAt(1, 0, 0).length, 0, 'a *_flower was given a collision box');
});

test('an unloaded cell has no collision — the streaming edge is not a wall', () => {
  const world = stubWorld(['minecraft:air', 'minecraft:stone']);
  const shapes = blockShapes(world, stubNav(false), physics);
  assert.equal(shapes.boxesAt(1, 0, 0).length, 0);
});

// ---------------------------------------------------------------------------
// modelBounds.

test('modelBounds unions the whole model and clamps it to the cell', () => {
  const quads = new Float32Array([0.25, 0.1, 0.25, 0.75, 0.9, 0.75, -0.5, 0.5, 1.5]);
  const got = modelBounds(quads);
  assert.ok(got, 'no bounds from a real model');
  // Float32Array, so compare with a tolerance rather than exactly: 0.1 stored as a float
  // reads back as 0.10000000149011612 and an exact compare would fail for no real reason.
  const want = [0, 0.1, 0.25, 0.75, 0.9, 1];
  for (let i = 0; i < 6; i++) {
    assert.ok(Math.abs(got[i] - want[i]) < 1e-6, `bound ${i}: got ${got[i]}, expected ${want[i]}`);
  }
});

test('modelBounds refuses a flat or empty model rather than returning a zero-volume box', () => {
  assert.equal(modelBounds(null), null);
  assert.equal(modelBounds(new Float32Array([])), null);
  // A flat plane (a carpet's top face alone) has no thickness and is not a collider.
  assert.equal(modelBounds(new Float32Array([0, 0.5, 0, 1, 0.5, 1])), null);
});

test('FULL_CUBE is what it says', () => {
  assert.deepEqual([...FULL_CUBE[0]], [0, 0, 0, 1, 1, 1]);
});
